"""Image generation via Google Gemini Imagen — text-to-image and image-reference flows.

Generated and reference images stay in memory and on S3; nothing is written to local disk.
"""

from __future__ import annotations

import asyncio
import io
import uuid
from typing import Optional

import requests
from fastapi import HTTPException, status
from google import genai
from google.genai import types
from PIL import Image

from app.core.config import settings
from app.core.logging import get_logger
from app.repositories.design_repository import DesignRepository
from app.schemas.responses import ImageGenerateResponse
from app.services.s3_service import upload_image as s3_upload

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ensure_gemini_configured() -> None:
    if not settings.gemini_api:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Gemini API key is not configured. Add Gemini_API to your .env file.",
        )


def _gemini_client() -> genai.Client:
    return genai.Client(api_key=settings.gemini_api)


def _upscale_to_target(raw_bytes: bytes) -> bytes:
    """Upscale generated bytes to the configured output size using Lanczos."""
    img = Image.open(io.BytesIO(raw_bytes)).convert("RGB")
    target = settings.image_output_size
    if img.size != target:
        img = img.resize(target, Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=False, compress_level=1)
    return buf.getvalue()


def _generate_with_reference(client: genai.Client, prompt: str, reference_bytes: bytes) -> bytes:
    response = client.models.generate_content(
        model=settings.imagen_reference_model,
        contents=[
            types.Content(parts=[
                types.Part(text=(
                    "Using the provided image as a visual reference, generate a new "
                    f"ring image based on this description: {prompt}"
                )),
                types.Part(inline_data=types.Blob(mime_type="image/png", data=reference_bytes)),
            ])
        ],
        config=types.GenerateContentConfig(response_modalities=["IMAGE", "TEXT"]),
    )
    for part in response.candidates[0].content.parts:
        if part.inline_data:
            return part.inline_data.data
    raise HTTPException(
        status_code=status.HTTP_502_BAD_GATEWAY,
        detail="Gemini returned no image in the response.",
    )


def _generate_from_prompt(client: genai.Client, prompt: str) -> bytes:
    response = client.models.generate_images(
        model=settings.imagen_text_model,
        prompt=prompt,
        config=types.GenerateImagesConfig(number_of_images=1),
    )
    if not response.generated_images:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Gemini returned no images.",
        )
    return response.generated_images[0].image.image_bytes


async def _fetch_remote_image(url: str) -> bytes:
    try:
        response = await asyncio.to_thread(requests.get, url, timeout=10)
    except requests.RequestException as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Error fetching reference image: {exc}",
        ) from exc
    if response.status_code != 200:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to fetch reference image: {url}",
        )
    return response.content


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def resolve_reference_bytes(
    *,
    explicit_url: Optional[str],
    design_reference_url: Optional[str],
) -> Optional[bytes]:
    """Pick the best reference URL (explicit overrides design's) and return its bytes."""
    url = explicit_url or design_reference_url
    if not url:
        return None
    return await _fetch_remote_image(url)


async def generate_for_design(
    *,
    design_id: int,
    prompt: str,
    reference_bytes: Optional[bytes],
    repo: DesignRepository,
) -> ImageGenerateResponse:
    """Generate an image, upload it to S3, and update the design record."""
    _ensure_gemini_configured()
    client = _gemini_client()

    try:
        if reference_bytes is not None:
            raw_bytes = await asyncio.to_thread(
                _generate_with_reference, client, prompt, reference_bytes
            )
        else:
            raw_bytes = await asyncio.to_thread(_generate_from_prompt, client, prompt)
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Gemini image generation failed")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Gemini image generation error: {exc}",
        ) from exc

    image_bytes = _upscale_to_target(raw_bytes)
    s3_key = f"generated/design_{design_id}/{uuid.uuid4().hex}.png"
    image_url = await asyncio.to_thread(s3_upload, s3_key, image_bytes, "image/png")

    await asyncio.to_thread(repo.set_generated_image, design_id, image_url)
    logger.info("Generated image for design %s → %s", design_id, image_url)

    return ImageGenerateResponse(image_url=image_url, prompt=prompt)
